`claimTo` for Drop and BundleDrop
nftlabs/nftlabs-sdk-ts pull request #156
Opened 2021-12-31 20:52 UTC by ayshptk

2022-01-01 00:09 UTC, jakeloo commented
@ayshptk let's not change the interface. claim should keep default to 0s

2022-01-02 01:42 UTC, atbe commented on src/modules/bundleDrop.ts
> +  public async claimTo(
docstring??

2022-01-02 01:42 UTC, atbe commented on src/modules/bundleDrop.ts
> +  private async prepareClaim(
docstring??

2022-01-02 01:42 UTC, atbe commented on src/modules/drop.ts
> +  private async prepareClaim(
docstring??

2022-01-02 01:42 UTC, atbe commented on src/modules/drop.ts
> +  public async claimTo(
docstring??

2022-01-03 20:27 UTC, atbe commented
Lets add tests for these new methods.

2022-01-04 08:15 UTC, ayshptk commented
@atbe added

2022-01-05 19:47 UTC, jakeloo requested changes

2022-01-05 19:47 UTC, jakeloo commented on src/modules/bundleDrop.ts
> +    data: BytesLike = [0],
we don't need to  expose this. hard it to `[0]` in the param.

2022-01-05 19:47 UTC, jakeloo commented on src/modules/drop.ts
> +  ): Promise<any> {
why any here?

2022-01-06 20:20 UTC, jakeloo approved these changes
you should be good, just minor clean up on docstring

2022-01-06 20:20 UTC, jakeloo commented on src/modules/bundleDrop.ts
> +   * @param data -
remove outdated docstring

2022-01-06 20:56 UTC, merged